'use client'

import { Loader2 } from 'lucide-react'
import ReactMarkdown from 'react-markdown'

interface LLMResponse {
  content: string
  provider?: string
  timestamp?: string
}

interface ResultsDisplayProps {
  results: string
  loading: boolean
}

function renderLLMResponse(response: LLMResponse) {
  return (
    <div className="llm-response">
      {response.provider && (
        <div className="text-sm text-gray-500 mb-2">
          Generated by {response.provider}
          {response.timestamp && ` at ${new Date(response.timestamp).toLocaleString()}`}
        </div>
      )}
      <div className="prose prose-lg max-w-none">
        <ReactMarkdown>{response.content}</ReactMarkdown>
      </div>
    </div>
  )
}

export default function ResultsDisplay({ results, loading }: ResultsDisplayProps) {
  if (loading) {
    return (
      <div className="max-w-4xl mx-auto text-center">
        <Loader2 className="animate-spin mx-auto mb-4" size={48} />
        <p className="text-lg text-gray-600">Searching the internet for information...</p>
      </div>
    )
  }

  if (!results) {
    return (
      <div className="max-w-4xl mx-auto text-center">
        <p className="text-lg text-gray-600">Enter a search query to get started.</p>
      </div>
    )
  }

  // For now, treat results as content; can be extended to parse structured response
  const llmResponse: LLMResponse = { content: results }

  return (
    <div className="max-w-4xl mx-auto">
      <div className="bg-white rounded-lg shadow-lg p-6">
        <h2 className="text-2xl font-bold mb-4">Search Results</h2>
        {renderLLMResponse(llmResponse)}
      </div>
    </div>
  )
}